name: Auto Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]  # Kiểm tra lại tên nhánh của bạn là 'main' hay 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ssh.pythonanywhere.com
        username: ${{ secrets.PA_USERNAME }}
        key: ${{ secrets.PA_SSH_KEY }}
        script: |
          # 1. Đi đến thư mục dự án
          cd /home/trieuvuong1997/project_8tieng

          git fetch --all
          git reset --hard origin/main
          # Lệnh reset --hard sẽ ép server giống hệt code trên GitHub, xóa bỏ các xung đột

          # 3. Cập nhật thư viện
          pip install --user -r requirements.txt

          # 4. Chạy lệnh Django
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput

          # 5. Khởi động lại Server
          touch /var/www/trieuvuong1997_pythonanywhere_com_wsgi.py