name: Auto Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]  # Kiểm tra lại tên nhánh của bạn là 'main' hay 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ssh.pythonanywhere.com
        username: ${{ secrets.PA_USERNAME }}
        key: ${{ secrets.PA_SSH_KEY }}
        script: |
          # 1. Đi đến thư mục dự án
          cd /home/trieuvuong1997/project_8tieng

          # 2. Lấy code mới nhất về
          git pull origin main

          # 3. Cập nhật thư viện (Dùng --user vì không có virtualenv)
          # Lưu ý: Nếu không có file requirements.txt thì có thể bỏ dòng này
          pip install --user -r requirements.txt

          # 4. Chạy lệnh Django cần thiết
          # (Dùng python3 để chắc chắn chạy đúng phiên bản)
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput

          # 5. Khởi động lại Server
          touch /var/www/trieuvuong1997_pythonanywhere_com_wsgi.py